#  Copyright (c) 2005-2006 Andre Merzky (andre@merzky.net)
# 
#  Use, modification and distribution is subject to the Boost Software
#  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt)

SAGA_ROOT        = ../../../../

SAGA_SUBDIRS     = ini process

SAGA_HDR         = utils.hpp is_local_address.hpp singleton.hpp filesystem.hpp
SAGA_SRC         = utils.cpp is_local_address.cpp
SAGA_OBJ         = utils.o is_local_address.o

include $(SAGA_ROOT)/make/saga.mk

