#  Copyright (c) 2005-2006 Andre Merzky (andre@merzky.net)
# 
#  Use, modification and distribution is subject to the Boost Software
#  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt)

SAGA_ROOT = ../

include $(SAGA_ROOT)/make/saga.util.mk

SAGA_SUBDIRS  += generator default

include $(SAGA_ROOT)/make/saga.mk

