#
#   Copyright (c) 2008 João Abecasis
#
#   Distributed under the Boost Software License, Version 1.0. (See accompanying
#   file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

SAGA_ROOT               = ../../../../

SAGA_SRC                = $(wildcard *.cpp)
SAGA_OBJ                = $(SAGA_SRC:%.cpp=%.o)
SAGA_BIN                = $(SAGA_SRC:%.cpp=%)

SAGA_USE_BOOST_OPTIONS  = yes
SAGA_DONT_INSTALL       = yes

include $(SAGA_ROOT)/make/saga.test.mk

