#!/bin/tcsh

unsetenv SAGA_VERBOSE

time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null
time saga-job submit ssh://localhost /usr/bin/sleep 10 > /dev/null

