
SAGA_ROOT = ../../

include $(SAGA_ROOT)/make/saga.util.mk

install::
	@$(ECHO)    "      installing adaptor skeletons"
	@$(INSTALL) -d skeleton                  $(SAGA_DAT_ROOT)/adaptor_generator/
	@$(INSTALL)    saga-adaptor-generator.pl $(SAGA_BIN_ROOT)/


include $(SAGA_ROOT)/make/saga.mk

