SAGA C++ API: saga::advert::entry Class Reference
saga::advert::entry Class Reference
The advert class represents an entry in a saga::advert::directory. An advert directory is a meta data directory with a hierarchical namespace attached. This class inherits all methods from saga::name_space::namespace_entry and provides additional methods to publish new and query existing adverts.
#include <advert.hpp>
Public Member Functions
entry (saga::session const &s, saga::url url, int mode=Read)
Constructs an advert object that points to url, opens it in mode and associates it with the session s.
entry (saga::url url, int mode=Read)
Constructs an advert object that points to url and opens it in mode.
entry (saga::object const &other)
Constructs a copy of other.
entry (void)
Constructs a default advert object.
~entry (void)
Destroys the advert object and frees all allocated resources.
void store_object (saga::object object)
Stores a saga object in this advert.
template<typename T >
boost::disable_if
< detail::has_sync_tag< T >
>::type store_object (T const &object)
saga::object retrieve_object ()
Retrieves the saga object stored in this advert.
template<typename T >
T & retrieve_object (typename boost::disable_if< detail::has_sync_tag< T > >::type *=0)
saga::object retrieve_object (saga::session const &s)
Retrieves the saga object stored in this advert and associates it with the session s.
SAGA_DEPRECATED (SAGA_ADVERT_DEPRECATED_MSG) void store_string(std
Stores a string in this advert.
SAGA_DEPRECATED (SAGA_ADVERT_DEPRECATED_MSG) std
Retrieves the string stored in this advert.
Static Public Member Functions
static entry create (session const &s, saga::url const &url, int mode=Read)
Factory function resembling entry(session, url, int) constructor.
static entry create (saga::url const &url, int mode=Read)
Factory function resembling entry(url, int) constructor.
template<typename Tag >
static saga::task create (saga::url const &url, int mode=Read)
Detailed Description
The advert class represents an entry in a saga::advert::directory. An advert directory is a meta data directory with a hierarchical namespace attached. This class inherits all methods from saga::name_space::namespace_entry and provides additional methods to publish new and query existing adverts.
Definition at line 110 of file packages/advert/advert.hpp.
Constructor & Destructor Documentation
saga::advert::entry::entry (saga::session const & s, saga::url url, int mode = Read)
Constructs an advert object that points to url, opens it in mode and associates it with the session s.
Definition at line 78 of file advert.cpp.
saga::advert::entry::entry (saga::url url, int mode = Read) [explicit]
Constructs an advert object that points to url and opens it in mode.
Definition at line 101 of file advert.cpp.
saga::advert::entry::entry (saga::object const & other) [explicit]
Constructs a copy of other.
Reimplemented from saga::name_space::entry.
Definition at line 133 of file advert.cpp.
References saga::object::Advert, saga::BadParameter, and saga::object::get_type().
saga::advert::entry::entry (void)
Constructs a default advert object.
Reimplemented from saga::name_space::entry.
Definition at line 124 of file advert.cpp.
saga::advert::entry::~entry (void)
Destroys the advert object and frees all allocated resources.
Reimplemented from saga::name_space::entry.
Definition at line 142 of file advert.cpp.
Member Function Documentation
static entry saga::advert::entry::create (session const & s, saga::url const & url, int mode = Read) [inline, static]
Factory function resembling entry(session, url, int) constructor.
Definition at line 180 of file packages/advert/advert.hpp.
static entry saga::advert::entry::create (saga::url const & url, int mode = Read) [inline, static]
Factory function resembling entry(url, int) constructor.
Definition at line 191 of file packages/advert/advert.hpp.
template<typename Tag > static saga::task saga::advert::entry::create (saga::url const & url, int mode = Read) [inline, static]
Definition at line 196 of file packages/advert/advert.hpp.
void saga::advert::entry::store_object (saga::object object) [inline]
Stores a saga object in this advert.
Parameters:
object The object to store
Definition at line 210 of file packages/advert/advert.hpp.
References saga::task::get_result().
template<typename T > boost::disable_if<detail::has_sync_tag<T> >::type saga::advert::entry::store_object (T const & object) [inline]
Definition at line 218 of file packages/advert/advert.hpp.
References saga::task::get_result().
saga::object saga::advert::entry::retrieve_object () [inline]
Retrieves the saga object stored in this advert.
Returns:
The object stored in this advert
Definition at line 242 of file packages/advert/advert.hpp.
References saga::task::get_result().
template<typename T > T& saga::advert::entry::retrieve_object (typename boost::disable_if< detail::has_sync_tag< T > >::type * = 0) [inline]
Definition at line 258 of file packages/advert/advert.hpp.
References saga::task::get_result().
saga::object saga::advert::entry::retrieve_object (saga::session const & s) [inline]
Retrieves the saga object stored in this advert and associates it with the session s.
Parameters:
s a session object
Returns:
The object stored in this advert
Definition at line 280 of file packages/advert/advert.hpp.
References saga::task::get_result().
saga::advert::entry::SAGA_DEPRECATED (SAGA_ADVERT_DEPRECATED_MSG) [inline]
Stores a string in this advert.
obsolete API below, don't use this anymore
Parameters:
str The string to store
Definition at line 301 of file packages/advert/advert.hpp.
References saga::task::get_result().
saga::advert::entry::SAGA_DEPRECATED (SAGA_ADVERT_DEPRECATED_MSG) [inline]
Retrieves the string stored in this advert.
Returns:
The string stored in this advert
Definition at line 322 of file packages/advert/advert.hpp.
References saga::task::get_result().
The documentation for this class was generated from the following files:
packages/advert/advert.hpp
advert.cpp