SAGA C++ API: saga::filesystem::directory Class Reference
saga::filesystem::directory Class Reference
The SAGA file package directory API.
#include <directory.hpp>
Public Member Functions
directory (session const &s, saga::url url, int mode=ReadWrite)
Open the directory.
directory (saga::url url, int mode=ReadWrite)
Open the directory.
directory (saga::object const &o)
Open the directory.
directory (void)
Open the directory.
~directory (void)
Destroy the directory object.
directory & operator= (saga::object const &o)
Brief description starts here.
saga::off_t get_size (saga::url url, int flags=None)
Returns the number of bytes in the file.
bool is_file (saga::url url)
Alias for is_entry in saga::ns_directory.
saga::filesystem::file open (saga::url url, int flags=saga::filesystem::Read)
Creates a new file instance.
saga::filesystem::directory open_dir (saga::url url, int flags=saga::filesystem::Read)
Creates a directory object.
Static Public Member Functions
static directory create (session const &s, saga::url url, int mode=Read)
Factory function resembling directory(session, url, int) constructor.
static directory create (saga::url url, int mode=Read)
Factory function resembling directory(url, int) constructor.
template<typename Tag >
static saga::task create (saga::url url, int mode=Read)
Factory function resembling entry(url, int) constructor.
Detailed Description
The SAGA file package directory API.
Definition at line 55 of file directory.hpp.
Constructor & Destructor Documentation
saga::filesystem::directory::directory (session const & s, saga::url url, int mode = ReadWrite)
Open the directory.
Definition at line 38 of file directory.cpp.
saga::filesystem::directory::directory (saga::url url, int mode = ReadWrite) [explicit]
Open the directory.
Definition at line 44 of file directory.cpp.
saga::filesystem::directory::directory (saga::object const & o) [explicit]
Open the directory.
Reimplemented from saga::name_space::directory.
Definition at line 50 of file directory.cpp.
References saga::BadParameter, saga::object::Directory, and saga::object::get_type().
saga::filesystem::directory::directory (void)
Open the directory.
Reimplemented from saga::name_space::directory.
Definition at line 59 of file directory.cpp.
saga::filesystem::directory::~directory (void)
Destroy the directory object.
Reimplemented from saga::name_space::directory.
Definition at line 63 of file directory.cpp.
Member Function Documentation
static directory saga::filesystem::directory::create (session const & s, saga::url url, int mode = Read) [inline, static]
Factory function resembling directory(session, url, int) constructor.
Reimplemented from saga::name_space::directory.
Definition at line 115 of file directory.hpp.
static directory saga::filesystem::directory::create (saga::url url, int mode = Read) [inline, static]
Factory function resembling directory(url, int) constructor.
Reimplemented from saga::name_space::directory.
Definition at line 123 of file directory.hpp.
template<typename Tag > static saga::task saga::filesystem::directory::create (saga::url url, int mode = Read) [inline, static]
Factory function resembling entry(url, int) constructor.
Reimplemented from saga::name_space::directory.
Definition at line 128 of file directory.hpp.
directory & saga::filesystem::directory::operator= (saga::object const & o)
Brief description starts here.
Reimplemented from saga::name_space::directory.
Definition at line 67 of file directory.cpp.
saga::off_t saga::filesystem::directory::get_size (saga::url url, int flags = None) [inline]
Returns the number of bytes in the file.
Returns:
Number of bytes in the file.
Parameters:
url Name of file to inspect.
Definition at line 146 of file directory.hpp.
References saga::task::get_result().
bool saga::filesystem::directory::is_file (saga::url url) [inline]
Alias for is_entry in saga::ns_directory.
Definition at line 160 of file directory.hpp.
References saga::task::get_result().
saga::filesystem::file saga::filesystem::directory::open (saga::url url, int flags = saga::filesystem::Read) [inline]
Creates a new file instance.
Parameters:
url File to be opened
flags,: Flags definition operation modus
Returns:
Opened file instance
Reimplemented from saga::name_space::directory.
Definition at line 177 of file directory.hpp.
References saga::task::get_result().
saga::filesystem::directory saga::filesystem::directory::open_dir (saga::url url, int flags = saga::filesystem::Read) [inline]
Creates a directory object.
Returns:
Opened directory instance
Parameters:
url Name of directory to open
flags Flags definition operation modus
Reimplemented from saga::name_space::directory.
Definition at line 195 of file directory.hpp.
References saga::task::get_result().
The documentation for this class was generated from the following files:
directory.hpp
directory.cpp