SAGA C++ API: saga::replica::logical_directory Class Reference
saga::replica::logical_directory Class Reference
A logical directory represents a directory entry in the name space of logical files.
#include <logical_directory.hpp>
Public Member Functions
logical_directory (session const &s, saga::url url, int mode=saga::replica::ReadWrite)
Creates the object.
logical_directory (saga::url url, int mode=saga::replica::ReadWrite)
Creates the object.
logical_directory (saga::object const &o)
Creates the object.
logical_directory (void)
Creates the object.
~logical_directory (void)
Destroys the object.
logical_directory & operator= (saga::object const &o)
Brief description starts here.
bool is_file (saga::url url)
Alias for is_entry of saga::ns_directory.
saga::replica::logical_file open (saga::url url, int flags=saga::replica::Read)
Creates a new logical_file instance.
saga::replica::logical_directory open_dir (saga::url url, int flags=saga::replica::Read)
Creates a new logical_directory instance.
std::vector< saga::url > find (std::string name_pattern, std::vector< std::string > key_pattern, int flags=saga::replica::Recursive)
Find entries in the current directory and below, with matching names and matching meta data.
Static Public Member Functions
static logical_directory create (session const &s, saga::url url, int mode=Read)
Factory function resembling logical_directory(session, url, int) constructor.
static logical_directory create (saga::url url, int mode=Read)
Factory function resembling logical_directory(url, int) constructor.
template<typename Tag >
static saga::task create (saga::url url, int mode=Read)
Factory function resembling entry(url, int) constructor.
Detailed Description
A logical directory represents a directory entry in the name space of logical files.
Several replica system implementations have the notion of containers, which, for our purposes, represent directories which can have, just as logical files, associated sets of meta data. In the presented API, logical directories and containers are the same.
Definition at line 75 of file logical_directory.hpp.
Constructor & Destructor Documentation
saga::replica::logical_directory::logical_directory (session const & s, saga::url url, int mode = saga::replica::ReadWrite)
Creates the object.
Definition at line 83 of file logical_directory.cpp.
saga::replica::logical_directory::logical_directory (saga::url url, int mode = saga::replica::ReadWrite) [explicit]
Creates the object.
Definition at line 107 of file logical_directory.cpp.
saga::replica::logical_directory::logical_directory (saga::object const & o) [explicit]
Creates the object.
Definition at line 130 of file logical_directory.cpp.
References saga::BadParameter, saga::object::get_type(), and saga::object::LogicalDirectory.
saga::replica::logical_directory::logical_directory (void)
Creates the object.
Definition at line 139 of file logical_directory.cpp.
saga::replica::logical_directory::~logical_directory (void)
Destroys the object.
Definition at line 148 of file logical_directory.cpp.
Member Function Documentation
static logical_directory saga::replica::logical_directory::create (session const & s, saga::url url, int mode = Read) [inline, static]
Factory function resembling logical_directory(session, url, int) constructor.
Reimplemented from saga::name_space::directory.
Definition at line 146 of file logical_directory.hpp.
static logical_directory saga::replica::logical_directory::create (saga::url url, int mode = Read) [inline, static]
Factory function resembling logical_directory(url, int) constructor.
Reimplemented from saga::name_space::directory.
Definition at line 155 of file logical_directory.hpp.
template<typename Tag > static saga::task saga::replica::logical_directory::create (saga::url url, int mode = Read) [inline, static]
Factory function resembling entry(url, int) constructor.
Reimplemented from saga::name_space::directory.
Definition at line 160 of file logical_directory.hpp.
logical_directory & saga::replica::logical_directory::operator= (saga::object const & o)
Brief description starts here.
Reimplemented from saga::name_space::directory.
Definition at line 152 of file logical_directory.cpp.
bool saga::replica::logical_directory::is_file (saga::url url) [inline]
Alias for is_entry of saga::ns_directory.
Definition at line 176 of file logical_directory.hpp.
References saga::task::get_result().
saga::replica::logical_file saga::replica::logical_directory::open (saga::url url, int flags = saga::replica::Read) [inline]
Creates a new logical_file instance.
Parameters:
url File to be opened
flags Flags definition operation modus
Returns:
Opened file instance
Reimplemented from saga::name_space::directory.
Definition at line 191 of file logical_directory.hpp.
References saga::task::get_result().
saga::replica::logical_directory saga::replica::logical_directory::open_dir (saga::url url, int flags = saga::replica::Read) [inline]
Creates a new logical_directory instance.
Parameters:
url Name of directory to open
flags Flags definition operation modus
Returns:
Opened directory instance
Reimplemented from saga::name_space::directory.
Definition at line 207 of file logical_directory.hpp.
References saga::task::get_result().
std::vector<saga::url> saga::replica::logical_directory::find (std::string name_pattern, std::vector< std::string > key_pattern, int flags = saga::replica::Recursive) [inline]
Find entries in the current directory and below, with matching names and matching meta data.
Parameters:
name_pattern Pattern for names of entries to be found
key_pattern Pattern for meta data of entries to be found
flags Flags defining the operation modus
Returns:
Array of names matching both pattern
Definition at line 226 of file logical_directory.hpp.
References saga::task::get_result().
The documentation for this class was generated from the following files:
logical_directory.hpp
logical_directory.cpp